# Generated by Django 5.2.5 on 2025-08-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LEARNER', 'Learner'), ('MENTOR', 'Mentor'), ('both', 'Both')], default='LEARNER', help_text='Designates whether the user is a learner, mentor, or both.', max_length=20),
        ),
    ]
