# Generated by Django 5.2.5 on 2025-08-16 21:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='review',
            name='learner',
            field=models.ForeignKey(blank=True, help_text='The learner who wrote the review.', limit_choices_to={'role': 'LEARNER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the review was created.'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('learner', 'content_type', 'object_id')},
        ),
    ]
