# Generated by Django 5.2.5 on 2025-08-16 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='learner',
            field=models.ForeignKey(limit_choices_to={'role__in': ['LEARNER', 'BOTH']}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='lessons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='lessons.lesson'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['lessons', 'scheduled_start'], name='bookings_bo_lessons_4e8f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['learner', 'status'], name='bookings_bo_learner_327f8d_idx'),
        ),
    ]
