# Generated by Django 5.2.5 on 2025-08-16 18:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-scheduled_start']},
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='content_type',
            field=models.ForeignKey(default=9, help_text='Content type of the booking, e.g., lesson.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='object_id',
            field=models.PositiveIntegerField(default=1, help_text='ID of the object being booked, e.g., lesson ID.'),
        ),
    ]
