# Generated by Django 5.2.5 on 2025-08-16 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_booking_booked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
