# Generated by Django 5.2.5 on 2025-08-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('delivery_type', models.CharField(choices=[('IN_PERSON', 'In Person'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], default='ONLINE', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('duration', models.PositiveBigIntegerField(help_text='Duration of the lesson per session in minutes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the lesson is currently active.')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
