# Generated by Django 5.2.5 on 2025-08-16 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='mentor',
            field=models.ForeignKey(help_text='The mentor who conducts the lesson.', limit_choices_to={'role__in': ['MENTOR', 'BOTH']}, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='skill',
            field=models.ForeignKey(help_text='The skill that the lesson is about.', on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='skills.skill'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['mentor', 'skill'], name='lessons_les_mentor__c97e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['price'], name='lessons_les_price_c4b111_idx'),
        ),
    ]
