# Generated by Django 5.2.5 on 2025-08-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_url',
            field=models.URLField(blank=True, help_text='URL to the lesson content, e.g., video or document.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the lesson in the list of lessons for a skill.'),
        ),
    ]
